name: Playwright Tests
run-name: ${{github.actor}} Run test Suite
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Clona todo lo que hay en el repositorio y lo coloca en un ambiente integrado
      
      - name: Install Node.js # Instalar Node 
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env :  
          COOKIE_NAME : ${{secrets.COOKIE_NAME}}
          COOKIE_VALUE : ${{secrets.COOKIE_VALUE}}
          COOKIE_DOMAIN : ${{secrets.COOKIE_DOMAIN}}
        run: npx playwright test

      - name: Generate Allure report 
        run: |
          npx allure generate allure-results -o allure-report

      - name: Deploy report to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./allure-report

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
